### ISSUE TITLE
How do you import/use external libraries?

### ISSUE THREAD

**Issue by dblock** [Gaweph/p5-typescript-starter#19]
What's the right way to import and use something like https://github.com/kazuhikoarase/qrcode-generator (or https://github.com/1w2w3y/qrcode-generator-ts) into this?

**Comment by Gaweph** [comment]
1) Add script tag to your `index.html`
`  <script src="https://cdnjs.cloudflare.com/ajax/libs/qrcode-generator/1.4.4/qrcode.min.js"></script>`

2) Add the typings to your project
`npm install -D qrcode-generator --save`

3) Add an import line in your `global.d.ts` file
`import qrcode = require('qrcode-generator');`

Note: I have updated the `tsconfig.json` file to include `"moduleResolution": "node"` (you can get the latest version of this repository or update this file on your own version)

The method outlined above means you can add the script tag to your html and get everything working without anything fancy like webpack etc...  keeping it simple (pure js and html).

Let me know if you get stuck.

**Comment by dblock** [comment]
This worked (https://github.com/dblock/p5qr), thank you. Maybe it could be a section in the README? I can queue it up for myself.

**Comment by Gaweph** [comment]
Brilliant.  Good idea.  Happy to include this in the readme.
