### ISSUE TITLE
SourceMap directory is incorrect

### ISSUE THREAD

**Issue by grantralls** [Gaweph/p5-typescript-starter#25]
By the tsc config, ts expects the source maps to be in `sketch/sketch/build.js.map`. The source maps are actually generated into `build/build.js.map`. I was able to fix the issue in my own project by changing the map root setting in tsconfig to `../build`.

You can confirm the issue by walking through the following process...
1. clone a clean copy of the repo.
2. `npm i`
3. `npm run start-compile`
4. check the last line in `build/build.js`

**Comment by grantralls** [comment]
It should be noted that the sourceRoot also needs to be updated to get the proper sources. I decided to remove both options sourceRoot and mapRoot to see if the automatic TS settings would do the trick and it did!

**Comment by Gaweph** [comment]
Good catch. Sorry for delay in responding. If you would like to do a PR with the relevant changes I would be happy to approve 👍

**Comment by grantralls** [comment]
#27
