### ISSUE TITLE
How to use clmtrackr

### ISSUE THREAD

**Issue by ihateids** [Gaweph/p5-typescript-starter#29]
I am having trouble using clmtrackr (https://github.com/auduno/clmtrackr) with the template. clm is undefined in the browser no matter what approach I use for import. The library works perfectly fine with public javascript p5 examples.

Using the same way as for qrcode library does not work (import clm = require('clmtrackr')). I would be very grateful for any help. My package.json:

"dependencies": {
    "clmtrackr": "^1.1.2",
    "qrcode-generator": "^1.4.4"
  },
  "devDependencies": {
    "@types/p5": "^1.3.3",
    "@types/clmtrackr": "^1.1.1",
    "browser-sync": "^2.26.12",
    "npm-run-all": "^4.1.5",
    "typescript": "^3.8.3"
  }

**Comment by Gaweph** [comment]
Have you added `<script src="js/clmtrackr.js"></script>` to your html header?

**Comment by ihateids** [comment]
Yes

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/clmtrackr/1.1.2/clmtrackr.module.min.js"
integrity="sha512-7OFCfpuVLXb+5EVhz0G2O5BYhfqvmMgiMmx3AJhgYSgwisUSLCW0R8JgHisRVKooL9SGhvu2IrGHkZ27GFTUug=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer">
  </script>
```

the module was fetched by the browser, http status 200:
![image](https://user-images.githubusercontent.com/16468622/151314647-83fd6ff6-ddf1-48e7-9cc5-e0b2546ec386.png)

This is in my global.d.ts:

```typescript
import * as p5Global from 'p5/global' 
import module = require('p5');
export = module;
export as namespace p5;

import qrcode = require('qrcode-generator');
import clm = require('clmtrackr');
```

and this is how it looks in sketch. linting shows that clm is unknown, and qrcode lib is ok:
![image](https://user-images.githubusercontent.com/16468622/151314989-54584fce-aae0-486c-bc63-4eea65c277b8.png)

**Comment by Gaweph** [comment]
Ok, so it appears that the `clm` is not defined correctly within `clmtrackr` `d.ts` file.

This will declare the variable properly for you :)

```js
// add to global.d.ts
import clmtrackr from 'clmtrackr';
declare global {namespace clm { class tracker extends clmtrackr.tracker {} }}
```

you can then do this (as per documentation found at: https://github.com/auduno/clmtrackr)
```js
// index.ts
var ctracker = new clm.tracker();
```
Let me know if you get stuck sir :)

**Comment by ihateids** [comment]
This is a great hack. linting works perfectly. Thank you :)

I am just still struggling with clm, it is undefined in browser :(
![image](https://user-images.githubusercontent.com/16468622/151331579-f4290313-9931-4de2-b588-2eb91897557b.png)

**Comment by Gaweph** [comment]
I think you might have pulled in the wrong js file from `https://cdnjs.com/libraries/clmtrackr`.  You want `clmtrackr.min.js` not `clmtrackr.module.min.js`

**Comment by ihateids** [comment]
omg, you are right :) Thank you so much for your help. How can I send you a cup of coffee, please ? Or beer?
