### ISSUE TITLE
Processing KEY constants are missing

### ISSUE THREAD

**Issue by tothambrus11** [Gaweph/p5-typescript-starter#5]
P5JS's `LEFT_ARROW`, `RIGHT_ARROW`, etc. are missing from the types. The code does compile but it would be better, if we didn't have to look at the errors.

**Comment by Gaweph** [comment]
Thanks for pointing this out.  Package updated to 0.9.0 which appears to have pulled in the key press constants as well as other things.

Reference here: https://p5js.org/reference/#/p5/keyPressed
