### ISSUE TITLE
createSlider seems to be undefined

### ISSUE THREAD

**Issue by sthaha** [Gaweph/p5-typescript-starter#6]
`createSlider` throws an `Uncaught ReferenceError: createSlider is not defined`
  
e.g.
```
function setup() {
  createCanvas(windowWidth, windowHeight)
}

function draw() {
  rect(width/2 - 40 , height/2 - 30, 80, 60)
}

let x = createSlider(0, 1, 10)
```

**Comment by sthaha** [comment]
https://github.com/Gaweph/p5-typescript-starter/issues/1#issuecomment-456405899 addresses this.

**Comment by Gaweph** [comment]
Sorry for delay in reply.  Glad you worked it out.  Since this has been mentioned more than once it might be worth adding the dom library to the default example.

**Comment by sthaha** [comment]
yes, I feel having it as default makes a lot of sense especially because `tsc` complies fine and you see the error only when you run it.  Alternatively, it may help if this is pointed out in the README.

Thanks @Gaweph for the quick start, it helped a lot!

**Comment by Gaweph** [comment]
@sthaha Dom and Sound libraries are now part of the default demo thanks for your input.
